### ISSUE TITLE
[ANDROID ERROR]: Unable to pause activity

### ISSUE THREAD

**Issue by KarandikarMihir** [auth0/react-native-auth0#113]
App crashes when `auth0.webAuth.authorize` is called..

```
11-16 15:08:43.960  1550  1562 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://tenant-name-99.auth0.com/... flg=0x50000000 cmp=com.android.chrome/com.google.android.apps.chrome.Main (has extras)} from uid 10079
11-16 15:08:43.966  5470  5470 D AndroidRuntime: Shutting down VM
11-16 15:08:43.967  5470  5470 E AndroidRuntime: FATAL EXCEPTION: main
11-16 15:08:43.967  5470  5470 E AndroidRuntime: Process: com.auth0native, PID: 5470
11-16 15:08:43.967  5470  5470 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {com.auth0native/com.auth0native.MainActivity}: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3912)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.app.ActivityThread.-wrap15(Unknown Source:0)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
11-16 15:08:43.967  5470  5470 E AndroidRuntime: Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7313)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1161)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.view.View.requestLayout(View.java:21995)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.view.ViewGroup.removeAllViews(ViewGroup.java:5400)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at com.facebook.react.devsupport.DebugOverlayController.setFpsDebugViewVisible(DebugOverlayController.java:49)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at com.facebook.react.devsupport.DevSupportManagerImpl.reload(DevSupportManagerImpl.java:940)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at com.facebook.react.devsupport.DevSupportManagerImpl.setDevSupportEnabled(DevSupportManagerImpl.java:480)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:529)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:551)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:119)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at com.facebook.react.ReactActivity.onPause(ReactActivity.java:60)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.app.Activity.performPause(Activity.java:7144)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3901)
11-16 15:08:43.967  5470  5470 E AndroidRuntime:        ... 11 more
11-16 15:08:43.979  1550  1566 I ActivityManager: Showing crash dialog for package com.auth0native u0
```

App.js-

```jsx
import React from 'react';
import Auth0 from 'react-native-auth0';

import { StyleSheet, Text, View, TouchableHighlight } from 'react-native';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.auth0 = new Auth0({ domain: 'tenant-name-99.auth0.com', clientId: 'xxxxxx' });
  }

  handlePress = () => {
    this.auth0
    .webAuth
    .authorize({scope: 'openid profile email', audience: 'https://tenant-name-99.auth0.com/userinfo'})
    .then(credentials => console.log(credentials))
    .catch(error => console.log(error));
  }

  render() {
    return (
      <View style={styles.container}>
        <TouchableHighlight onPress={this.handlePress}>
          <Text>Click me</Text>
        </TouchableHighlight>
        <Text style={styles.heading}>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  }
});
```

**Comment by KarandikarMihir** [comment]
Downgrading Android version of emulator to API23 solved this. Closing.
